### ISSUE TITLE
Seeded random crate

### ISSUE THREAD

**Issue by matteojug** [distributed-lab/bpcon#11]
For seeded random, is there a specific reason you used [seeded-random](https://crates.io/crates/seeded-random)? It doesn't seem a very popular crate, was it vetted somehow?

**Comment by nikitamasych** [comment]
We need cryptographically secure and portable random generator, thus we relied on this crate instead of `StdRng` for example; it is just a convenient wrapper around `rand_chacha`. Yet indeed, you are correct that it is not really maintable (for instance link to repo is wrong), so I changed it to use `rand_chacha` directly in #18
